Refactor CANInterface to support RX interrupts
solarcaratuva/TemplateCode pull request #20
Opened 2021-06-13 20:01 UTC by edward-noe

Closes #18. This PR adds support for RX interrupts by adding a queue (with a default size of 64 CAN messages) of Mbed events. In the `rx_isr()` method, CAN messages are added to the queue. In the `rx_handler()` method, messages are processed by calling `can_parser.parse()`. 

Notably, this PR relies on disabling the mutex in the Mbed CAN class. This allows for `can.read()` to be called in an ISR context, even with RTOS enabled. This is accomplished in the new `NoMutexCAN.h` file.

2021-06-14 03:54 UTC, rjserpe18 requested changes
These are my comments for now, not sure about thread safe nature but I will look into this/start a discussion in embedded chat.

2021-06-14 03:54 UTC, rjserpe18 commented on Common/lib/CANInterface/CANInterface.cpp
> -        CANMessage receivedCANMessage;
Should this be defined a second time? Seems like initialization at the beginning of the method is sufficient.

2021-06-14 03:54 UTC, rjserpe18 commented on PowerAux/src/main.cpp
> +CANInterface vehicle_can_interface(CAN2_RX, CAN2_TX, vehicle_can_parser, vehicle_can_rx_thread, vehicle_can_tx_thread, &vehicle_can_stby, CAN_PERIOD);
can we continue with the BMS_CAN/VEHICLE_CAN scheme here as opposed to CAN_xx/CAN2_xx? I feel like it's more descriptive.

2021-06-15 00:12 UTC, edward-noe commented
Since we can't be 100% confident in the thread-safety of this code, I'll close the PR for now. We can potentially do a similar refactor in the future if Mbed's STM CAN interrupt implementation is fixed in the future.

2021-06-15 00:12 UTC, closed without merging